name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out Github Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically trigger by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server"
      - run: echo "The name of your branch is ${{ github.ref }}"
      - run: echo "The name of your repo is ${{ github.repository }}"
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "${{ github.repository }} repo was cloned to the runner"
      - run: echo "Workflow now ready to test code on the runner"
      - name: List files in the repo
        run: |
          ls ${{ github.workspace }}
      - run: echo "The job's status is ${{ job.status }}"
